views:
  helm.toolkit.fluxcd.io/v2beta1/helmreleases:
    sortColumn: NAME:asc
    columns:
      - NAME
      - READY
      - STATUS
      - SUSPENDED:.spec.suspend
      - AGE
  helm.toolkit.fluxcd.io/v2/helmreleases:
    sortColumn: NAME:asc
    columns:
      - NAME
      - READY
      - STATUS
      - SUSPENDED:.spec.suspend
      - AGE
  kustomize.toolkit.fluxcd.io/v1/kustomizations:
    sortColumn: NAME:asc
    columns:
      - NAME
      - READY
      - STATUS
      - SUSPENDED:.spec.suspend
      - AGE
  external-secrets.io/v1/externalsecrets:
    sortColumn: NAME:asc
    columns:
      - NAME
      - STORETYPE|H
      - STORE|H
      - STATUS
      - READY
      - REFRESH INTERVAL
      - UPDATED:.status.refreshTime|T
      - AGE:.metadata.creationTimestamp|T
