views:
  helm.toolkit.fluxcd.io/v2/helmreleases:
    sortColumn: NAME:asc
    columns:
      - NAME
      - READY
      - STATUS
      - SUSPENDED:.spec.suspend
      - AGE
  kustomize.toolkit.fluxcd.io/v1/kustomizations:
    sortColumn: NAME:asc
    columns:
      - NAME
      - READY
      - STATUS
      - SUSPENDED:.spec.suspend
      - AGE
